# Site settings
title: 'Senior Custom Upholstery & Furniture'
email: 'sales@seniorchairs.com'
description: 'Toronto based manufacturers and importers of chrome and wood chairs, barstools, and oak edge tables for restaurants, banquet halls, hotels and institutions.'
url: 'http://localhost:4000'
baseurl: '/seniorchairs'

# Build settings
permalink: 'pretty'
include: ['_pages', '.htaccess']
exclude: ['Gemfile', 'Gemfile.lock', 'node_modules', 'package.json', 'Gruntfile.js']
gems: ['jekyll-sitemap']

sass:
  sass_dir: 'assets/styles/_scss'
  style: 'compressed'

markdown: 'kramdown'
kramdown:
  parse_block_html: true

# Folder based sorting
defaults:
  - scope:
      path: '_pages/chairs'
    values:
      layout: 'item'
      type: 'chair'
  - scope:
      path: '_pages/barstools'
    values:
      layout: 'item'
      type: 'barstool'
  - scope:
      path: '_pages/tables'
    values:
      layout: 'item'
      type: 'table'
  - scope:
      path: '_pages/booths'
    values:
      layout: 'item'
      type: 'booth'